### ISSUE TITLE
[GCDAsyncSocket closeWithError:] crash, iOS16

### ISSUE THREAD

**Issue by jcexk** [robbiehanson/CocoaAsyncSocket#823] opened 2023-04-15 17:51 UTC
```
OS Version:      iOS 16.4 (20E247)

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000001f3abe1e4
Crashed Thread:  18


Thread 18 Crashed:
0   libsystem_platform.dylib        0x00000001f3abe1e4 __os_unfair_lock_recursive_abort (in libsystem_platform.dylib) + 36
1   libsystem_platform.dylib        0x00000001f3ab907c __os_unfair_lock_lock_slow (in libsystem_platform.dylib) + 284
2   CoreFoundation                  0x000000019429b44c _CFSocketInvalidate (in CoreFoundation) + 132
3   CFNetwork                       0x0000000195346770 _CFNetworkErrorGetLocalizedDescription + 314456
4   CoreFoundation                  0x00000001941e3e88 _CFArrayApplyFunction (in CoreFoundation) + 72
5   CFNetwork                       0x0000000195323a94 _CFNetworkErrorGetLocalizedDescription + 171900
6   CoreFoundation                  0x000000019424a024 __CFRelease (in CoreFoundation) + 284
7   CoreFoundation                  0x000000019429b780 _CFSocketInvalidate (in CoreFoundation) + 952
8   CFNetwork                       0x00000001953304e4 _CFNetworkErrorGetLocalizedDescription + 223692
9   CoreFoundation                  0x0000000194210838 __CFStreamClose (in CoreFoundation) + 108
10  XXX                     0x00000001072dee1c -[GCDAsyncSocket closeWithError:] (in XXX) (AsyncSocket/GCDAsyncSocket.m:3239)
11  XXX                     0x00000001072e306c -[GCDAsyncSocket doReadEOF] (in XXX) (AsyncSocket/GCDAsyncSocket.m:5722)
12  XXX                     0x00000001072e1ab8 __66-[GCDAsyncSocket setupReadAndWriteSourcesForNewlyConnectedSocket:]_block_invoke (in XXX) (AsyncSocket/GCDAsyncSocket.m:4284)
13  libdispatch.dylib               0x000000019b695eac __dispatch_client_callout (in libdispatch.dylib) + 20
14  libdispatch.dylib               0x000000019b699330 __dispatch_continuation_pop (in libdispatch.dylib) + 504
15  libdispatch.dylib               0x000000019b6ac908 __dispatch_source_invoke (in libdispatch.dylib) + 1588
16  libdispatch.dylib               0x000000019b69d40c __dispatch_lane_serial_drain (in libdispatch.dylib) + 372
17  libdispatch.dylib               0x000000019b69e0a4 __dispatch_lane_invoke (in libdispatch.dylib) + 384
18  libdispatch.dylib               0x000000019b6a8cdc __dispatch_workloop_worker_thread (in libdispatch.dylib) + 648
19  libsystem_pthread.dylib         0x00000001f3b4fddc __pthread_wqthread (in libsystem_pthread.dylib) + 288
```
thanks

**Comment by silverhammermba** [comment] 2023-04-19 18:15
Almost certainly a duplicate of #803

**Comment by boazFrenkel** [comment] 2023-06-07 08:49
I have the same issue!
Looks like it started from iOS 16.4

**Comment by zhuozhuo** [comment] 2023-06-16 11:15
+1

**Closed as completed** 2023-08-23 00:15 UTC
Labels: no-issue-activity

**Comment by juchanglong** [comment] 2024-11-08 02:01
@jcexk Is your problem solved?

**Comment by dustturtle** [comment] 2026-03-05 05:37
https://github.com/dustturtle/NWAsyncSocket 为彻底解决此问题，基于network.framework 重写的 tcp socket框架（oc版本api和gcdasyncsocket兼容，替换直接可用），battle tested yet. Any problem , contact me !
